### ISSUE TITLE
document what library to use with a new C project

### ISSUE THREAD

**Issue by eiro** [shlomif/libtap-prev#1]
hello Shlomi,

* 2 TAP producers are mentioned here: https://testanything.org/producers.html#c
* you mentioned on your site https://www.shlomifish.org/open-source/projects/libtap/ that https://github.com/zorgnax/libtap seems better. also: the project have more contributors.
* both projects are updated this year.

can you tell us the  pros and cons of those libraries in the README or even in https://github.com/TestAnything/testanything.github.io ?

regards
regards

**Comment by shlomif** [comment]
Updated the readme mentioning cmocka - thanks for the report.

**Comment by eiro** [comment]
the readme now points to a fork of zorgnax/libtap. isn't it better to point on the repo maintained by @zorgnax ?

**Comment by shlomif** [comment]
@eiro : my fork has some branches with unmerged enhancements.

**Comment by eiro** [comment]
hello @shlomif,

On Fri, Aug 02, 2019 at 07:08:36AM -0700, Shlomi Fish wrote:
> @eiro : my fork has some branches with unmerged enhancements.

good to know. out of curiosity: if it's still relevant to maintain that
library, wouldn't it be nice to propose a PR?

regards
marc

**Comment by shlomif** [comment]
@eiro : hi, see https://github.com/zorgnax/libtap/pull/14 but I feel that cmocka is preferable anyway.

**Comment by eiro** [comment]
thanks for sharing. well ... i have to admit i understand @zorgnax reaction: make is a common unix tool, cmake is not. for such a simple project, i don't think it's worth adding this dependency.

regards
